name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Immunisation-Batch-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: ./templates/deploy-stage.yml
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    environment: internal-dev
    post_init:
        - template: ./templates/post-deploy.yml       
      # - environment: internal-dev-sandbox
      #   proxy_path: sandbox
      #   post_deploy:
      #     - template: ./templates/run-tests.yml
      #   trying pipeline execution
