name: "$(SourceBranchName)+$(BuildID)"

pool:
  name: 'AWS-ECS'

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ['*']

variables:
  - template: project.yml

steps:
  - bash: |
      BUILDKIT_PROGRESS=plain docker build --target test -t imms-batch-build -f batch.Dockerfile .

    displayName: Test batch code
    workingDirectory: "$(Pipeline.Workspace)/s/$(SERVICE_NAME)/batch"