name: "$(SourceBranchName)+$(BuildID)"

pool:
  name: 'AWS-ECS'

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ['*']

variables:
  - template: project.yml

jobs:
  - job: build
    displayName: Build & Test
    timeoutInMinutes: 30
    pool:
      name: 'AWS-ECS'
    workspace:
      clean: all
    steps:
      - bash: |
          BUILDKIT_PROGRESS=plain docker build --target test -t imms-batch-build -f batch.Dockerfile .

        displayName: Test lambda code
        workingDirectory: "$(Pipeline.Workspace)/s/$(SERVICE_NAME)/batch"
        #trying pipeline runrr
