steps:
    - bash: |
        set -e
        mkdir -p ~/.aws
        rm -f ~/.aws/config || true
        echo '[default]' > ~/.aws/config
        echo 'region = eu-west-2' >> ~/.aws/config
        echo 'output = json' >> ~/.aws/config
        chmod 600 ~/.aws/config
        cp ~/.aws/config ~/.aws/config.default
      displayName: clean aws config