parameters:
  - name: service_name
    type: string
    default:'immunisation-batch'
  - name: short_service_name
    type: string
    default:'imms-batch'

stages:
  - stage: Internal-Dev
    jobs:
      - template: deploy-stage.yml
        parameters:
          service_name: ${{ parameters.service_name }}
          short_service_name: ${{ parameters.short_service_name }}
          environment: internal-dev
          post_init:
              - template: post-deploy.yml
  - stage: Integration
    dependsOn: Internal-Dev
    jobs:
      - template: deploy-stage.yml
        parameters:
          service_name: ${{ parameters.service_name }}
          short_service_name: ${{ parameters.short_service_name }}
          environment: int
          post_init:
              - template: post-deploy.yml
  - stage: Reference
    dependsOn: Integration
    jobs:
    - template: deploy-stage.yml
      parameters:
        service_name: ${{ parameters.service_name }}
        short_service_name: ${{ parameters.short_service_name }}
        environment: ref
        post_init:
            - template: post-deploy.yml