parameters:
  - name: reviewers
    type: object
    default: []
jobs:
  - job: ApprovalJob
    displayName: "Manual Approval Job"
    steps:
      - task: ManualValidation@0
        inputs:
          instructions: "Please approve the deployment."
          onTimeout: "reject"
          timeoutInMinutes: 10
          reviewers: ${{ parameters.reviewers }}