jobs:  
- job: waitForValidation
  displayName: Wait for external validation  
  pool: server    
  timeoutInMinutes: 60 # job times out in 3 days
  steps:   
  - task: ManualValidation@0
    timeoutInMinutes: 10 # task times out in 1 day
    inputs:
      notifyUsers: |
        VAAL1@hscic.gov.uk
      instructions: 'Please validate the build configuration and resume'
      onTimeout: 'resume'