parameters:
  - name: manual_approval_env
    type: string

jobs:
  - job: deploy
    displayName: Manual Approval Required
    timeoutInMinutes: 30
    pool:
      vmImage: "ubuntu-latest"
    environment: ${{ parameters.manual_approval_env }}
      approvals:
      - reviewers:
          - id: 'VAAL1@hscic.gov.uk'
    strategy:
      runOnce:
        deploy:
          steps:
            - bash: |
                echo Approved