class Constant:
    valid_vaccine_type = ["flu", "covid19", "mmr"]
    valid_versions = ["v5"]
    valid_ods_codes = ["YGM41", "8J1100001", "8HK48", "YGA", "0DE", "0DF", "8HA94", "X26", "YGMYH",
                       "W00", "W000", "ZT001", "YA7", "N2N9I", "YGJ"]
    expected_csv_content = [
        'NHS_NUMBER', 'PERSON_FORENAME', 'PERSON_SURNAME', 'PERSON_DOB', 'PERSON_GENDER_CODE', 'PERSON_POSTCODE',
        'DATE_AND_TIME', 'SITE_CODE', 'SITE_CODE_TYPE_URI', 'UNIQUE_ID', 'UNIQUE_ID_URI', 'ACTION_FLAG',
        'PERFORMING_PROFESSIONAL_FORENAME', 'PERFORMING_PROFESSIONAL_SURNAME', 'RECORDED_DATE', 'PRIMARY_SOURCE',
        'VACCINATION_PROCEDURE_CODE', 'VACCINATION_PROCEDURE_TERM', 'DOSE_SEQUENCE', 'VACCINE_PRODUCT_CODE',
        'VACCINE_PRODUCT_TERM', 'VACCINE_MANUFACTURER', 'BATCH_NUMBER', 'EXPIRY_DATE', 'SITE_OF_VACCINATION_CODE',
        'SITE_OF_VACCINATION_TERM', 'ROUTE_OF_VACCINATION_CODE', 'ROUTE_OF_VACCINATION_TERM', 'DOSE_AMOUNT',
        'DOSE_UNIT_CODE', 'DOSE_UNIT_TERM', 'INDICATION_CODE', 'LOCATION_CODE', 'LOCATION_CODE_TYPE_URI'
    ]
    invalid_csv_content = (
        "INVALID_HEADER1,INVALID_HEADER2,INVALID_HEADER3,INVALID_HEADER4,INVALID_HEADER5,INVALID_HEADER6,"
        "INVALID_HEADER7,INVALID_HEADER8,INVALID_HEADER9,INVALID_HEADER10,INVALID_HEADER11,INVALID_HEADER12,"
        "INVALID_HEADER13,INVALID_HEADER14,INVALID_HEADER15,INVALID_HEADER16,INVALID_HEADER17,INVALID_HEADER18,"
        "INVALID_HEADER19,INVALID_HEADER20,INVALID_HEADER21,INVALID_HEADER22,INVALID_HEADER23,INVALID_HEADER24,"
        "INVALID_HEADER25,INVALID_HEADER26,INVALID_HEADER27,INVALID_HEADER28,INVALID_HEADER29,INVALID_HEADER30,"
        "INVALID_HEADER31,INVALID_HEADER32,INVALID_HEADER33,INVALID_HEADER34"
    )
