name: Build & Test code

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
 test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Change to filenameprocessor directory
       run: |
            cd filenameprocessor
            ls -l
     - name: Build the Docker image
       uses: docker/build-push-action@v4
       with:
         context: .
         file: filenameprocessor/Dockerfile
         tags: imms-batch-build
         target: test