name: Coverage report

on:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      - name: Set up AWS credentials
        env:
          AWS_ACCESS_KEY_ID: "FOOBARKEY"
          AWS_SECRET_ACCESS_KEY: "FOOBARSECRET"
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY  

      - name: Install dependencies
        run: |
          pip install poetry moto==4.2.11 coverage redis botocore==1.35.49 simplejson

      - name: Run unit tests and generate coverage report for filenameprocessor
        run: |
          mkdir -p /home/runner/work/immunisation-batch/immunisation-batch/filenameprocessor/coverage_html_report
          poetry run coverage run -m unittest discover -s tests
          poetry run coverage report
          poetry run coverage xml -o /home/runner/work/immunisation-batch/immunisation-batch/filenameprocessor/coverage_html_report/filenameprocessor_coverage.xml
        working-directory: "/home/runner/work/immunisation-batch/immunisation-batch/filenameprocessor"
        continue-on-error: true

      - name: Run unit tests and generate coverage report for recordprocessor
        run: |
          mkdir -p /home/runner/work/immunisation-batch/immunisation-batch/recordprocessor/coverage_html_report
          poetry run coverage run -m unittest discover -s tests
          poetry run coverage report
          poetry run coverage xml -o /home/runner/work/immunisation-batch/immunisation-batch/recordprocessor/coverage_html_report/recordprocessor_coverage.xml
        working-directory: "/home/runner/work/immunisation-batch/immunisation-batch/recordprocessor"
        continue-on-error: true

      - name: Run unit tests and generate coverage report for recordforwarder
        run: |
          mkdir -p /home/runner/work/immunisation-batch/immunisation-batch/recordforwarder/coverage_html_report
          poetry run coverage run -m unittest discover -s tests
          poetry run coverage report
          poetry run coverage xml -o /home/runner/work/immunisation-batch/immunisation-batch/recordforwarder/coverage_html_report/recordforwarder_coverage.xml
        working-directory: "/home/runner/work/immunisation-batch/immunisation-batch/recordforwarder"
        continue-on-error: true

      - name: List coverage report file
        run: |
          ls -R /home/runner/work/immunisation-batch/immunisation-batch/filenameprocessor/coverage_html_report
          ls -R /home/runner/work/immunisation-batch/immunisation-batch/recordprocessor/coverage_html_report
          ls -R /home/runner/work/immunisation-batch/immunisation-batch/recordforwarder/coverage_html_report

      - name: Aggregate coverage reports
        run: |
          mkdir -p /home/runner/work/immunisation-batch/immunisation-batch/coverage_html_report
          rm -rf /home/runner/work/immunisation-batch/immunisation-batch/coverage_html_report/*
          mv /home/runner/work/immunisation-batch/immunisation-batch/filenameprocessor/coverage_html_report/filenameprocessor_coverage.xml /home/runner/work/immunisation-batch/immunisation-batch/coverage_html_report/filenameprocessor_coverage.xml
          mv /home/runner/work/immunisation-batch/immunisation-batch/recordprocessor/coverage_html_report/recordprocessor_coverage.xml /home/runner/work/immunisation-batch/immunisation-batch/coverage_html_report/recordprocessor_coverage.xml
          mv /home/runner/work/immunisation-batch/immunisation-batch/recordforwarder/coverage_html_report/recordforwarder_coverage.xml /home/runner/work/immunisation-batch/immunisation-batch/coverage_html_report/recordforwarder_coverage.xml

     

      - name: Commit and push coverage reports
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin ${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
          git pull origin ${{ github.head_ref }}
          git add /home/runner/work/immunisation-batch/immunisation-batch/coverage_html_report/*.xml
          git commit -m "Add coverage index as XML"
          git push origin ${{ github.head_ref }}
      
          - name: Upload Coverage to SonarQube
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          run: |
            sonar-scanner \
            -Dsonar.projectKey=NHSDigital_immunisation-batch \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.python.coverage.reportPaths=coverage-report/*.xml