name: sonarcloud
on: pull_request
jobs:
  sonar_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Sonar Scanner
        run: |
          wget -O sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-4.6.2.2472-linux sonar-scanner
          export PATH="${PATH}:${GITHUB_WORKSPACE}/sonar-scanner/bin"
          
      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PATH: "${{ github.workspace }}/sonar-scanner/bin:${{ env.PATH }}"
        run: |
          sonar-scanner \
          -Dsonar.projectKey=NHSDigital_immunisation-batch \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN \
          -Dsonar.python.coverage.reportPaths=filenameprocessor_coverage.xml
