name: sonarcloud
on: pull_request
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and other packages
        run: pip install tox
        working-directory: ./immunisation-batch  # specify the working directory
      - name: Run tox
        run: tox -e py
        working-directory: ./immunisation-batch  # specify the working directory
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          working-directory: ./immunisation-batch  # specify the working directory
